name: Helix (Debian 11,12)

# Based on https://github.com/helix-editor/helix/blob/master/.github/workflows/release.yml

on:
  workflow_dispatch:

env:
  MAIN_URL: "https://github.com/helix-editor/helix/archive/refs/tags/23.05.tar.gz"
  NAME_SOURCE: "helix-editor.tar.gz"
  NAME_SOURCE_STEM: "helix-editor"
  RELEASE_NAME: "helix"

jobs:
  fetch-grammars:
    name: Fetch Grammars
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        # uses: actions/checkout@v4
        run: |
          wget "${{ env.MAIN_URL }}" -O "${{ env.NAME_SOURCE }}"
          tar -xvf "${{ env.NAME_SOURCE }}"
          mv -v $"{{ env.NAME_SOURCE_STEM }}" "_"
          mv -v _/* ./
          rm -v "${{ env.NAME_SOURCE }}"
          rmdir -v "_"

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Fetch tree-sitter grammars
        run: cargo run --package=helix-loader --bin=hx-loader

      - name: Bundle grammars
        run: tar cJf grammars.tar.xz -C runtime/grammars/sources .

      - uses: actions/upload-artifact@v3
        with:
          name: grammars
          path: grammars.tar.xz

  dist:
    name: Dist
    needs: [fetch-grammars]
    env:
      # For some builds, we use cross to test on 32-bit and big-endian
      # systems.
      CARGO: cargo
      # When CARGO is set to CROSS, this is set to `--target matrix.target`.
      TARGET_FLAGS:
      # When CARGO is set to CROSS, TARGET_DIR includes matrix.target.
      TARGET_DIR: ./target
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # don't fail other jobs if one fails
      matrix:
        build: [x86_64-linux] #, x86_64-win-gnu, win32-msvc
        include:
        - build: x86_64-linux
          os: ubuntu-20.04
          rust: stable
          target: x86_64-unknown-linux-gnu
          cross: false
          
