# This is a basic workflow to help you get started with Actions

name: See

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      URL:
        description: "Url"
        required: True
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Create workspace
        run: mkdir workspace

      - name: Download and extract
        working-directory: workspace
        run: |
          FILENAME=$(printf ${{ inputs.URL }}|rev|cut -d / -f 1|rev)
          wget "${{ inputs.URL }}" -O "$FILENAME"
          tar -xvf "$FILENAME"
          rm -v "$FILENAME"
          find .
