# This is a basic workflow to help you get started with Actions

name: See

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      URL:
        description: "Url"
        required: True
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Download and see
        run: |
          mkdir files
          wget "${{ inputs.URL }}" -O files/
          find files/
